### ISSUE TITLE
Final Things

### ISSUE THREAD

**Issue by daniel-j-henderson** [drwhich/Exquisite-Corpse#4]
I added the scrolly images, as you can see the images are all filler ones right now, so you can replace the image with your name in the img folder with one that is more appropriate. 

Additionally, We can change that title too, and the footer, and add in any other little pieces too. Lupe, I'd say maybe try to do your hover/image popup thing with that image of the mask that Brady put in. You could put it at the first mention of the mask maybe, I don't know.

**Comment by daniel-j-henderson** [comment]
And Lupe I added your text that was in that word document

**Comment by elhi5671** [comment]
I pulled and then added my image background. I just pushed it. Ill look for
more little things to edit to make it more aesthetically pleasing. lemme
know if theres more i should do

**Comment by elhi5671** [comment]
I see that our site is repeating the story twice in a row. I'm looking at it right now but not fully understanding why this is happening

**Comment by daniel-j-henderson** [comment]
Ok the problem is that when merge conflicts occur, you have to deal with them, otherwise it will just put a weird and meaningless mixture of the 2 pieces of code that are having conflicts. I'm fixing it, and this class isn't really in-depth enough to go over how to avoid and fix merge conflicts so I'd say don't worry about it. That being said, if somebody wants to find a couple more themed images as th backgrounds that would be helpful.

**Comment by daniel-j-henderson** [comment]
Everything should be working now. Make sure you pull all changes before committing any new changes and don't push anything when there's merge conflicts.
